### ISSUE TITLE
After 1.1.3, some builds fail

### ISSUE THREAD

**Issue by chriskrycho** [rwjblue/git-repo-info#19]
This is a fun one. Since the 1.13 publication, builds started failing for us on our TeamCity server, but _only_ there. We can't reproduce locally (on OS X 10.11.5 or Windows 10 Pro).

The call to `findRepo()` is returning `null`, and that error condition isn't being handled: it's just passing the result directly into `path.join`, [here](https://github.com/rwjblue/git-repo-info/blob/v1.1.3/index.js#L128). Curiously, 1.13 didn't actually change anything around this—but something about shipping it did break the TC build.

Our TeamCity box is running Windows Server 2008 and Git [will add shortly].

Here's the full stack trace:

``` plain
TypeError: Path must be a string. Received null
    at assertPath (path.js:8:11)
    at Object.win32.resolve (path.js:130:5)
    at module.exports (D:\BuildAgent\work\8afa5390471260e3\node_modules\git-repo-info\index.js:128:16)
    at version (D:\BuildAgent\work\8afa5390471260e3\node_modules\git-repo-version\index.js:11:14)
    at Class.module.exports.config (D:\BuildAgent\work\8afa5390471260e3\node_modules\ember-cli-app-version\index.js:10:46)
    at D:\BuildAgent\work\8afa5390471260e3\node_modules\ember-cli\lib\models\project.js:223:27
    at Array.reduce (native)
    at Project.getAddonsConfig (D:\BuildAgent\work\8afa5390471260e3\node_modules\ember-cli\lib\models\project.js:221:22)
    at Project.config (D:\BuildAgent\work\8afa5390471260e3\node_modules\ember-cli\lib\models\project.js:199:29)
    at Class.module.exports._monkeyPatch_EmberDeprecate (D:\BuildAgent\work\8afa5390471260e3\node_modules\ember-cli-deprecation-workflow\index.js:62:41)
    at Class.module.exports.setupPreprocessorRegistry (D:\BuildAgent\work\8afa5390471260e3\node_modules\ember-cli-deprecation-workflow\index.js:114:12)
    at D:\BuildAgent\work\8afa5390471260e3\node_modules\ember-cli-preprocess-registry\preprocessors.js:27:13
    at Array.forEach (native)
    at setupRegistryForEachAddon (D:\BuildAgent\work\8afa5390471260e3\node_modules\ember-cli-preprocess-registry\preprocessors.js:25:10)
    at Object.module.exports.setupRegistry (D:\BuildAgent\work\8afa5390471260e3\node_modules\ember-cli-preprocess-registry\preprocessors.js:46:3)
    at new EmberApp (D:\BuildAgent\work\8afa5390471260e3\node_modules\ember-cli\lib\broccoli\ember-app.js:108:5)
```

**Comment by novaugust** [comment]
this isn't just windows, came here after investigating build failures for our heroku release

**Comment by chriskrycho** [comment]
@novaugust interesting. I updated the title accordingly; does your error output show anything different than mine?

**Comment by novaugust** [comment]
Was just lookig at that to compare. Answer: same stack

**Comment by rwjblue** [comment]
Anyone have a repro locally?

**Comment by drewnichols** [comment]
This is also failing for me on all my heroku deploys

**Comment by novaugust** [comment]
@rwjblue yeah, figured it out.
Clone your ember project somewhere and delete its `.git` folder

Without that, the path comes back null, et voila.

**Comment by drewnichols** [comment]
removing git folder worked for me as well locally

**Comment by rwjblue** [comment]
Why would this have changed between 1.1.2 and 1.1.3?

**Comment by rwjblue** [comment]
Got it.  Fix incoming.

**Comment by Samsinite** [comment]
:+1:, this broke our heroku deploys as well. You are on top of everything @rwjblue.

**Comment by rwjblue** [comment]
Released v1.1.4

**Comment by drewnichols** [comment]
worked in heroku, thanks @rwjblue!

**Comment by Voles** [comment]
Works again using Docker, thanks @rwjblue!
